### PR TITLE
Remove deprecated action for tagging

### PR DESCRIPTION
**Pull request by pureskube**
Tagging is done automatically by the release action, so this one is not needed any more.

### CODE REVIEW

**Comment by pure-mgupta** [comment]
will this merge create a new release?

**Comment by pureskube** [comment]
No, because version check will fail. We should add something like `if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'release')` to the publish flow though

**Comment by sdodsley** [comment]
To create a new release will require a special PR to build the new docs, changelogs, etc.
At that point I will submit the release tarball to Red Hat and build the associated execution environment
Let me know when you are ready to cut a new release - ie all your patches are ready and merged

**Review by pure-mgupta — APPROVED** [review]

**Comment by pureskube** [comment]
@pure-mgupta I don't have write permissions, so I can't merge the PR. Can please one of you guys do it? Thank you!

**Pull request merged**
